show:
  DamageDisplay: true
  HealthBar: true

tag:
  DamageDisplay: "marumasa.DamageDisplay"
  HealthBar: "marumasa.HealthBar"

hideList:
  DamageDisplay: [ ]
  HealthBar: [ "ender_dragon","wither","allay" ]